### ISSUE TITLE
change "MidiFile" into "smf::MidiFile"

### ISSUE THREAD

**Issue by ToverPomelo** [davidgranstrom/json-to-midi#4]
When I make, I get the error:

` g++  -g -std=c++11 -Wall -pedantic -I include -c -o build/json-to-midi.o src/json-to-midi.cpp
src/json-to-midi.cpp:76:27: error: variable or field ‘createMidiNoteEvents’ declared void
 void createMidiNoteEvents(MidiFile &midifile, int track, double timeScale, json event)
                           ^
src/json-to-midi.cpp:76:27: error: ‘MidiFile’ was not declared in this scope
src/json-to-midi.cpp:76:27: note: suggested alternative:
In file included from src/json-to-midi.cpp:7:0:
include/MidiFile.h:39:7: note:   ‘smf::MidiFile’
 class MidiFile {
       ^
src/json-to-midi.cpp:76:37: error: ‘midifile’ was not declared in this scope
 void createMidiNoteEvents(MidiFile &midifile, int track, double timeScale, json event)
                                     ^
src/json-to-midi.cpp:76:47: error: expected primary-expression before ‘int’
 void createMidiNoteEvents(MidiFile &midifile, int track, double timeScale, json event)
                                               ^
src/json-to-midi.cpp:76:58: error: expected primary-expression before ‘double’
 void createMidiNoteEvents(MidiFile &midifile, int track, double timeScale, json event)
                                                          ^
src/json-to-midi.cpp:76:81: error: expected primary-expression before ‘event’
 void createMidiNoteEvents(MidiFile &midifile, int track, double timeScale, json event)
                                                                                 ^
Makefile:20: recipe for target 'build/json-to-midi.o' failed
make: *** [build/json-to-midi.o] Error 1
`

I think you should change "MidiFile" into "smf::MidiFile" in line 76 104 and 130?

**Comment by davidgranstrom** [comment]
Thanks for the report. Unfortunately I can't reproduce the error. 

Did you run the build script `build-libmidifile.sh` first? Also, which platform are you using? I've only tested this on macOS so far.

**Comment by ToverPomelo** [comment]
I tried this on Ubuntu 16.04
`gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10) `

**Comment by davidgranstrom** [comment]
I think you are using a newer version of the Midifile library. `namespace smf` was introduced in [this commit](https://github.com/craigsapp/midifile/commit/d798e3e66c763b0f59ace2f1bde12339d39ddb73#diff-08c6c499a6e731b4ca7ba26a5fc4be76). Try and checkout commit 1e3caf102c571152a9374853e093d4ad0d78d889 in the midifile submodule and see if that helps.

**Comment by ToverPomelo** [comment]
OK and I will close the issue😀
